# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-21 04:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specifiedchromosome', models.CharField(max_length=300)),
                ('chrom_start', models.BigIntegerField(null=True)),
                ('chrom_end', models.BigIntegerField(null=True)),
                ('bed_line_name', models.CharField(max_length=400, null=True)),
                ('score', models.IntegerField(null=True)),
                ('strand', models.CharField(max_length=2, null=True)),
                ('thickstart', models.BigIntegerField(null=True)),
                ('thickend', models.BigIntegerField(null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BedFileModel',
            fields=[
                ('bed_id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=300, null=True)),
                ('track_name', models.CharField(max_length=300, null=True)),
                ('bed_type', models.CharField(max_length=128, null=True)),
                ('file_description', models.CharField(max_length=300, null=True)),
                ('visibility', models.IntegerField(null=True)),
                ('itemrgb', models.CharField(max_length=4, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='beddata',
            name='bedfilemodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genome.BedFileModel'),
        ),
    ]
